language: php

php:
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: 7.1

script:
  make test

before_script:
  - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d && echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer selfupdate
  - travis_wait composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
